import { defaultThemeTokens } from "@/lib/theme";
import type {
  CmsPage,
  FooterColumnDto,
  GalleryCollectionDto,
  LocaleCode,
  MemberDto,
  NeighborhoodArchiveItem,
  NavigationItemDto,
  ThemeTokens,
} from "@/types/cms";

export const fallbackTheme: ThemeTokens = defaultThemeTokens;

export const fallbackNavigation: Record<LocaleCode, NavigationItemDto[]> = {
  en: [
    { id: "nav-en-who", label: "WHO WE ARE", path: "/en/who-we-are", sortOrder: 1, isVisible: true },
    { id: "nav-en-what", label: "WHAT WE DO", path: "/en/what-we-do", sortOrder: 2, isVisible: true },
    { id: "nav-en-members", label: "FOUNDING MEMBERS", path: "/en/founding-members", sortOrder: 3, isVisible: true },
    { id: "nav-en-gallery", label: "PHOTO GALLERY", path: "/en/photo-gallery", sortOrder: 4, isVisible: true },
    { id: "nav-en-neighborhood-archive", label: "NEIGHBORHOOD ARCHIVE", path: "/en/neighborhood-archive", sortOrder: 5, isVisible: true },
  ],
  ar: [
    { id: "nav-ar-who", label: "من نحن", path: "/ar/who-we-are", sortOrder: 1, isVisible: true },
    { id: "nav-ar-what", label: "ماذا نفعل", path: "/ar/what-we-do", sortOrder: 2, isVisible: true },
    { id: "nav-ar-members", label: "الأعضاء المؤسسون", path: "/ar/founding-members", sortOrder: 3, isVisible: true },
    { id: "nav-ar-gallery", label: "معرض الصور", path: "/ar/photo-gallery", sortOrder: 4, isVisible: true },
  ],
};

export const fallbackFooter: Record<LocaleCode, FooterColumnDto[]> = {
  en: [
    {
      id: "footer-en-main",
      title: "LORA",
      sortOrder: 1,
      content: {
        text: "Luweibdeh old residents association",
        location: "Amman, Paris square",
        phone: "+962 7 7930 6500",
        email: "info@lorajo.org",
      },
      links: [],
    },
  ],
  ar: [
    {
      id: "footer-ar-main",
      title: "لورا",
      sortOrder: 1,
      content: {
        text: "جمعية سكان جبل اللويبدة القدامى",
        location: "عمان، ميدان باريس",
        phone: "+962 7 7930 6500",
        email: "info@lorajo.org",
      },
      links: [],
    },
  ],
};

export const fallbackMembers: MemberDto[] = [
  { id: "member-omar", name: "Omar T. Alfaouri", slug: "omar-t-alfaouri", title: "Founding member", image: null, sortOrder: 1 },
  {
    id: "member-wael",
    name: "Wael Hamza Smadi",
    slug: "wael-hamza-smadi",
    title: "Founding member",
    image: { src: "/lora/founders/wael-hamza-smadi.jpg", alt: "Wael Hamza Smadi" },
    sortOrder: 2,
  },
  {
    id: "member-saleem",
    name: "Saleem Quna",
    slug: "saleem-quna",
    title: "Founding member",
    image: { src: "/lora/founders/saleem-quna.jpg", alt: "Saleem Quna" },
    sortOrder: 3,
  },
  {
    id: "member-reem",
    name: "Reem Farkouh",
    slug: "reem-farkouh",
    title: "Founding member",
    image: { src: "/lora/founders/reem-farkouh.jpg", alt: "Reem Farkouh" },
    sortOrder: 4,
  },
  {
    id: "member-rami",
    name: "Rami Daher",
    slug: "rami-daher",
    title: "Founding member",
    image: { src: "/lora/founders/rami-daher.jpg", alt: "Rami Daher" },
    sortOrder: 5,
  },
  {
    id: "member-muneer",
    name: "Muneer Al Kurdi",
    slug: "muneer-al-kurdi",
    title: "Founding member",
    image: { src: "/lora/founders/muneer-al-kurdi.jpg", alt: "Muneer Al Kurdi" },
    sortOrder: 6,
  },
  {
    id: "member-marwan",
    name: "Marwan Al Manha",
    slug: "marwan-al-manha",
    title: "Founding member",
    image: { src: "/lora/founders/marwan-al-manha.jpg", alt: "Marwan Al Manha" },
    sortOrder: 7,
  },
  {
    id: "member-ali",
    name: "Ali Al Manha",
    slug: "ali-al-manha",
    title: "Founding member",
    image: { src: "/lora/founders/ali-al-manha.jpg", alt: "Ali Al Manha" },
    sortOrder: 8,
  },
  {
    id: "member-majdolin",
    name: "Majdolin Ghazawi",
    slug: "majdolin-ghazawi",
    title: "Founding member",
    image: { src: "/lora/founders/majdolin-ghazawi.jpg", alt: "Majdolin Ghazawi" },
    sortOrder: 9,
  },
  { id: "member-abuazzam", name: "Marwan Abuazzam", slug: "marwan-abuazzam", title: "Founding member", image: null, sortOrder: 10 },
];

export const fallbackGallery: GalleryCollectionDto[] = [
  {
    id: "collection-historical",
    title: "HISTORICAL PHOTOS",
    slug: "historical-photos",
    description: "Archival views and memory fragments from Jabal Al-Luweibdeh.",
    sortOrder: 1,
    images: [
      { src: "/lora/gallery/square-de-paris.jpg", alt: "Paris Square", caption: "Paris Square" },
      { src: "/lora/gallery/luweibdeh-flower.jpg", alt: "Luweibdeh Flower", caption: "Luweibdeh Flower" },
      { src: "/lora/gallery/blue-house-4.jpg", alt: "Blue House", caption: "Blue House" },
    ],
  },
  {
    id: "collection-landmarks",
    title: "LANDMARKS",
    slug: "landmarks",
    description: "Civic, cultural, and architectural landmarks in the neighborhood.",
    sortOrder: 2,
    images: [
      { src: "/lora/gallery/dar-al-anda-art-gallery.jpg", alt: "Dar Al-Anda", caption: "Dar Al-Anda" },
      { src: "/lora/gallery/alsaadi-mosque.jpg", alt: "Al Saadi Mosque", caption: "Al Saadi Mosque" },
    ],
  },
  {
    id: "collection-figures",
    title: "FAMOUS FIGURES",
    slug: "famous-figures",
    description: "Residents and public figures connected to Luweibdeh history.",
    sortOrder: 3,
    images: [
      { src: "/lora/founders/wael-hamza-smadi.jpg", alt: "Wael Hamza Smadi", caption: "Wael Hamza Smadi" },
      { src: "/lora/founders/reem-farkouh.jpg", alt: "Reem Farkouh", caption: "Reem Farkouh" },
      { src: "/lora/founders/saleem-quna.jpg", alt: "Saleem Quna", caption: "Saleem Quna" },
    ],
  },
];

export const fallbackNeighborhoodArchive: NeighborhoodArchiveItem[] = [
  {
    id: "archive-paris-square",
    name: "Paris Square",
    text: "A civic meeting point in Jabal Al-Luweibdeh.",
    mediaType: "IMAGE",
    src: "/lora/gallery/square-de-paris.jpg",
    thumbnail: "/lora/gallery/square-de-paris.jpg",
    folder: "Fallback archive",
  },
  {
    id: "archive-dar-al-anda",
    name: "Dar Al-Anda",
    text: "A cultural landmark in the neighborhood archive.",
    mediaType: "IMAGE",
    src: "/lora/gallery/dar-al-anda-art-gallery.jpg",
    thumbnail: "/lora/gallery/dar-al-anda-art-gallery.jpg",
    folder: "Fallback archive",
  },
  {
    id: "archive-blue-house",
    name: "Blue House",
    text: "Architectural memory from Luweibdeh.",
    mediaType: "IMAGE",
    src: "/lora/gallery/blue-house-4.jpg",
    thumbnail: "/lora/gallery/blue-house-4.jpg",
    folder: "Fallback archive",
  },
];

export const fallbackPages: Record<LocaleCode, Record<string, CmsPage>> = {
  en: {
    home: {
      id: "page-en-home",
      locale: "en",
      slug: "home",
      title: "LORA",
      seoTitle: "LORA - Luweibdeh Old Residents Association",
      seoDescription: "LORA preserves Jabal Al-Luweibdeh's historical architecture, greenery, and cultural heritage.",
      status: "PUBLISHED",
      sections: [
        {
          id: "home-hero",
          type: "hero",
          variant: "editorial_fullscreen",
          sortOrder: 1,
          isVisible: true,
          content: {
            eyebrow: "Luweibdeh Old Residents Association",
            title: "LORA",
            subtitle: "Luweibdeh Old Residents Association",
            tagline: "Our cultural heritage is our identity",
            body: "A civic association preserving Jabal Al-Luweibdeh's historical architecture, greenery, cultural memory, and community life.",
            image: "/lora/gallery/luweibdeh-flower.jpg",
            logo: "/lora/brand/lora-logo.png",
            cta: { label: "Read More", href: "/en/who-we-are" },
          },
          settings: {
            imagePlacement: "background",
            overlayOpacity: 0.45,
            parallax: true,
            titleTop: "LORA",
            titleBottom: "LUWEIBDEH",
            accentHex: "#01963c",
            defaultAspect: 16 / 9,
            heroScrubFrames: [
              "/lora/gallery/luweibdeh-flower.jpg",
              "/lora/gallery/square-de-paris.jpg",
              "/lora/gallery/dar-al-anda-art-gallery.jpg",
              "/lora/gallery/blue-house-4.jpg",
              "/lora/gallery/alsaadi-mosque.jpg",
              "/lora/gallery/luzmila-hospital.jpg",
              "/lora/gallery/dscf0022.jpg",
              "/lora/gallery/luweibdeh-flower-2.jpg",
            ],
          },
          background: { token: "black" },
        },
        {
          id: "home-marquee",
          type: "text_marquee",
          variant: "heritage_line",
          sortOrder: 2,
          isVisible: true,
          content: { items: ["Heritage Preservation", "Community Engagement", "Sustainability", "Equity"] },
          settings: { speed: 32 },
          spacing: { top: "small", bottom: "small" },
          background: { token: "parchment" },
        },
        {
          id: "home-story",
          type: "heritage_story",
          variant: "overlapping_editorial",
          sortOrder: 3,
          isVisible: true,
          content: {
            label: "What we do ?",
            title: "Protecting a neighborhood without freezing it in time.",
            body: "LORA aims to enhance community engagement and improve services in the neighborhood in cultural, environmental, and heritage aspects.",
            image: "/lora/gallery/square-de-paris.jpg",
            cta: { label: "Read More", href: "/en/what-we-do" },
          },
          settings: { imagePlacement: "right", cardStyle: "stone_border" },
          background: { token: "softWhite" },
        },
        {
          id: "home-gallery",
          type: "gallery_grid",
          variant: "lightbox_grid",
          sortOrder: 4,
          isVisible: true,
          content: {
            title: "Luweibdeh in fragments",
            items: [
              { src: "/lora/gallery/square-de-paris.jpg", alt: "Paris Square", caption: "Paris Square" },
              { src: "/lora/gallery/dar-al-anda-art-gallery.jpg", alt: "Dar Al-Anda", caption: "Dar Al-Anda" },
              { src: "/lora/gallery/blue-house-4.jpg", alt: "Blue House", caption: "Blue House" },
              { src: "/lora/gallery/alsaadi-mosque.jpg", alt: "Al Saadi Mosque", caption: "Al Saadi Mosque" },
              { src: "/lora/gallery/luweibdeh-flower.jpg", alt: "Luweibdeh Flower", caption: "Luweibdeh Flower" },
              { src: "/lora/gallery/luzmila-hospital.jpg", alt: "Luzmila Hospital", caption: "Luzmila Hospital" },
              { src: "/lora/gallery/dscf0022.jpg", alt: "Luweibdeh street detail", caption: "Street detail" },
            ],
          },
          settings: { columns: 4, lightbox: true },
          background: { token: "parchment" },
        },
        {
          id: "home-newsletter",
          type: "newsletter_signup",
          variant: "centered_minimal",
          sortOrder: 5,
          isVisible: true,
          content: {
            title: "Stay close to the neighborhood.",
            body: "Receive LORA updates on cultural, environmental, and heritage initiatives.",
            buttonLabel: "Subscribe",
          },
          settings: {},
          background: { token: "black" },
        },
      ],
    },
    "who-we-are": {
      id: "page-en-who",
      locale: "en",
      slug: "who-we-are",
      title: "LORA JO",
      seoTitle: "Who We Are - LORA",
      seoDescription: "The Association of Old Residents of Jabal Al-Luweibdeh.",
      status: "PUBLISHED",
      sections: [
        {
          id: "who-hero",
          type: "hero",
          variant: "centered_minimal",
          sortOrder: 1,
          isVisible: true,
          content: {
            title: "LORA JO",
            subtitle: "The Association of Old Residents of Jabal Al-Luweibdeh (LORA)",
          },
          settings: {},
        },
        {
          id: "who-body",
          type: "rich_text",
          variant: "editorial_body",
          sortOrder: 2,
          isVisible: true,
          content: {
            body: [
              "Established in 2024 at the initiative of a group of long-time residents, LORA is dedicated to preserving Luweibdeh's historical buildings, natural landscape, streets, and greenery in the face of the assault of modern trends of architectural urbanization and serving its community members.",
              "Its main activities include supporting all private and public initiatives to make this neighborhood attractive for cultural and artistic activities.",
              "LORA aspires to create a dynamic, engaged community that honors its past while looking forward to a sustainable and promising future.",
              "LORA voluntarily and equitably provides services to all its members, with no intention of generating financial profit or offering personal benefits, either directly or indirectly to its board members. It consciously avoids political, sectarian, and personal agendas.",
            ],
          },
          settings: {},
        },
      ],
    },
    "what-we-do": {
      id: "page-en-what",
      locale: "en",
      slug: "what-we-do",
      title: "What we do ?",
      seoTitle: "What We Do - LORA",
      seoDescription: "LORA community, heritage, environmental, and local economic initiatives.",
      status: "PUBLISHED",
      sections: [
        {
          id: "what-hero",
          type: "hero",
          variant: "split_text_image",
          sortOrder: 1,
          isVisible: false,
          content: { title: "What we do ?", image: "/lora/gallery/dar-al-anda-art-gallery.jpg" },
          settings: {},
        },
        {
          id: "what-body",
          type: "rich_text",
          variant: "what_we_do_gallery",
          sortOrder: 2,
          isVisible: true,
          content: {
            title: "What we do ?",
            subtitle: "LORA strengthens belonging, protects shared heritage, and supports practical community initiatives.",
            images: [
              { src: "/lora/gallery/dar-al-anda-art-gallery.jpg", alt: "Dar Al-Anda", caption: "Cultural activity" },
              { src: "/lora/gallery/square-de-paris.jpg", alt: "Paris Square", caption: "Public space" },
              { src: "/lora/gallery/alsaadi-mosque.jpg", alt: "Al Saadi Mosque", caption: "Heritage landmark" },
              { src: "/lora/gallery/blue-house-4.jpg", alt: "Blue House", caption: "Historical architecture" },
            ],
            body: [
              "The founding committee has outlined two primary objectives:",
              "1. Fostering a Sense of Belonging: LORA aims to enhance community engagement and improve services in the neighborhood in cultural, environmental, and heritage aspects.",
              "This will be achieved through research, documentation, skill development programs, lectures, seminars, and workshops tailored to the community, especially younger generations.",
              "LORA will spare no effort to analyze the neighborhood's challenges and issues and work with proper authorities to address them.",
              "2. Organizing Small Income-Generating Projects: LORA seeks to collaborate with residents to operate small-scale projects that benefit the community and individual participants.",
              "Programs include enhancing the economic well-being of Al-Luweibdeh residents, creating new job opportunities, and hosting a seasonal bazaar in collaboration with specialized local organizations.",
            ],
          },
          settings: {},
        },
      ],
    },
    "founding-members": {
      id: "page-en-members",
      locale: "en",
      slug: "founding-members",
      title: "LORA",
      seoTitle: "Founding Members - LORA",
      seoDescription: "LORA founding members.",
      status: "PUBLISHED",
      sections: [
        {
          id: "members-hero",
          type: "hero",
          variant: "centered_minimal",
          sortOrder: 1,
          isVisible: false,
          content: {
            title: "LORA",
            subtitle: "Dedication. Expertise. Passion.",
            oldImportedContent:
              "This is your Team section. It's a great place to introduce your team and talk about what makes it special, such as your culture or work philosophy. Don't be afraid to illustrate personality and character to help users connect with your team.",
          },
          settings: { showOldImportedContent: false },
        },
        {
          id: "members-grid",
          type: "member_grid",
          variant: "team_showcase",
          sortOrder: 2,
          isVisible: true,
          content: { title: "Founding members", subtitle: "Dedication. Expertise. Passion.", source: "members" },
          settings: {},
        },
      ],
    },
    "photo-gallery": {
      id: "page-en-gallery",
      locale: "en",
      slug: "photo-gallery",
      title: "PHOTO GALLERY",
      seoTitle: "Photo Gallery - LORA",
      seoDescription: "Historical photos, landmarks, and famous figures connected to Jabal Al-Luweibdeh.",
      status: "PUBLISHED",
      sections: [
        {
          id: "gallery-hero",
          type: "hero",
          variant: "centered_minimal",
          sortOrder: 1,
          isVisible: false,
          content: { title: "PHOTO GALLERY" },
          settings: {},
        },
        {
          id: "gallery-collections",
          type: "gallery_masonry",
          variant: "staggered_grid",
          sortOrder: 2,
          isVisible: true,
          content: {
            title: "PHOTO GALLERY",
            subtitle: "Historical photos, landmarks, and public memory from Jabal Al-Luweibdeh.",
            collections: ["HISTORICAL PHOTOS", "LANDMARKS", "FAMOUS FIGURES"],
          },
          settings: {},
        },
      ],
    },
    "neighborhood-archive": {
      id: "page-en-neighborhood-archive",
      locale: "en",
      slug: "neighborhood-archive",
      title: "Neighborhood Archive",
      seoTitle: "Neighborhood Archive - LORA",
      seoDescription: "A searchable library of neighborhood names, photos, videos, and memory fragments from Jabal Al-Luweibdeh.",
      status: "PUBLISHED",
      sections: [
        {
          id: "neighborhood-archive-main",
          type: "neighborhood_archive",
          variant: "searchable_library",
          sortOrder: 1,
          isVisible: true,
          content: {
            title: "Neighborhood Archive",
            subtitle: "Search names, photographs, videos, and memory fragments connected to Jabal Al-Luweibdeh.",
          },
          settings: {},
          background: { token: "softWhite" },
        },
      ],
    },
  },
  ar: {
    home: {
      id: "page-ar-home",
      locale: "ar",
      slug: "home",
      title: "لورا",
      seoTitle: "لورا - جمعية سكان جبل اللويبدة القدامى",
      seoDescription: "جمعية سكان جبل اللويبدة القدامى.",
      status: "PUBLISHED",
      sections: [
        {
          id: "home-hero-ar",
          type: "hero",
          variant: "editorial_fullscreen",
          sortOrder: 1,
          isVisible: true,
          content: {
            eyebrow: "جمعية سكان جبل اللويبدة القدامى",
            title: "لورا",
            subtitle: "جمعية سكان جبل اللويبدة القدامى",
            tagline: "تراثنا الثقافي هو هويتنا",
            body: "جمعية مجتمعية تعمل على حفظ عمارة جبل اللويبدة التاريخية وخضرته وذاكرته الثقافية.",
            image: "/lora/gallery/luweibdeh-flower.jpg",
            logo: "/lora/brand/lora-logo.png",
            cta: { label: "اقرأ المزيد", href: "/ar/who-we-are" },
          },
          settings: {
            imagePlacement: "background",
            overlayOpacity: 0.45,
            parallax: true,
            titleTop: "LORA",
            titleBottom: "LUWEIBDEH",
            accentHex: "#01963c",
            defaultAspect: 16 / 9,
            heroScrubFrames: [
              "/lora/gallery/luweibdeh-flower.jpg",
              "/lora/gallery/square-de-paris.jpg",
              "/lora/gallery/dar-al-anda-art-gallery.jpg",
              "/lora/gallery/blue-house-4.jpg",
              "/lora/gallery/alsaadi-mosque.jpg",
              "/lora/gallery/luzmila-hospital.jpg",
              "/lora/gallery/dscf0022.jpg",
              "/lora/gallery/luweibdeh-flower-2.jpg",
            ],
          },
          background: { token: "black" },
        },
        {
          id: "home-story-ar",
          type: "heritage_story",
          variant: "overlapping_editorial",
          sortOrder: 2,
          isVisible: true,
          content: {
            label: "ماذا نفعل؟",
            title: "حفظ الحي مع إبقائه حيا.",
            body: "تسعى لورا إلى تعزيز انتماء المجتمع وتحسين الخدمات في الجوانب الثقافية والبيئية والتراثية.",
            image: "/lora/gallery/square-de-paris.jpg",
            cta: { label: "اقرأ المزيد", href: "/ar/what-we-do" },
          },
          settings: {},
        },
      ],
    },
    "who-we-are": {
      id: "page-ar-who",
      locale: "ar",
      slug: "who-we-are",
      title: "لورا",
      seoTitle: "من نحن - لورا",
      seoDescription: "جمعية سكان جبل اللويبدة القدامى.",
      status: "PUBLISHED",
      sections: [
        {
          id: "who-ar",
          type: "hero",
          variant: "centered_minimal",
          sortOrder: 1,
          isVisible: true,
          content: { title: "لورا", subtitle: "جمعية سكان جبل اللويبدة القدامى" },
          settings: {},
        },
      ],
    },
    "what-we-do": {
      id: "page-ar-what",
      locale: "ar",
      slug: "what-we-do",
      title: "ماذا نفعل",
      seoTitle: "ماذا نفعل - لورا",
      seoDescription: "مبادرات لورا التراثية والمجتمعية.",
      status: "PUBLISHED",
      sections: [
        {
          id: "what-ar",
          type: "hero",
          variant: "centered_minimal",
          sortOrder: 1,
          isVisible: true,
          content: { title: "ماذا نفعل؟" },
          settings: {},
        },
      ],
    },
    "founding-members": {
      id: "page-ar-members",
      locale: "ar",
      slug: "founding-members",
      title: "الأعضاء المؤسسون",
      seoTitle: "الأعضاء المؤسسون - لورا",
      seoDescription: "الأعضاء المؤسسون لجمعية لورا.",
      status: "PUBLISHED",
      sections: [
        {
          id: "members-ar",
          type: "member_grid",
          variant: "team_showcase",
          sortOrder: 1,
          isVisible: true,
          content: { title: "الأعضاء المؤسسون", subtitle: "تفان. خبرة. شغف.", source: "members" },
          settings: {},
        },
      ],
    },
    "photo-gallery": {
      id: "page-ar-gallery",
      locale: "ar",
      slug: "photo-gallery",
      title: "معرض الصور",
      seoTitle: "معرض الصور - لورا",
      seoDescription: "صور تاريخية ومعالم وشخصيات من جبل اللويبدة.",
      status: "PUBLISHED",
      sections: [
        {
          id: "gallery-ar",
          type: "gallery_masonry",
          variant: "staggered_grid",
          sortOrder: 1,
          isVisible: true,
          content: {
            title: "معرض الصور",
            subtitle: "صور تاريخية ومعالم وذاكرة عامة من جبل اللويبدة.",
            collections: ["HISTORICAL PHOTOS", "LANDMARKS", "FAMOUS FIGURES"],
          },
          settings: {},
        },
      ],
    },
    "neighborhood-archive": {
      id: "page-ar-neighborhood-archive",
      locale: "ar",
      slug: "neighborhood-archive",
      title: "Neighborhood Archive",
      seoTitle: "Neighborhood Archive - LORA",
      seoDescription: "A searchable library of neighborhood names, photos, videos, and memory fragments from Jabal Al-Luweibdeh.",
      status: "PUBLISHED",
      sections: [
        {
          id: "neighborhood-archive-ar-main",
          type: "neighborhood_archive",
          variant: "searchable_library",
          sortOrder: 1,
          isVisible: true,
          content: {
            title: "Neighborhood Archive",
            subtitle: "Search names, photographs, videos, and memory fragments connected to Jabal Al-Luweibdeh.",
          },
          settings: {},
          background: { token: "softWhite" },
        },
      ],
    },
  },
};
