import { defaultThemeTokens } from "@/lib/theme";
import type {
  CmsPage,
  FooterColumnDto,
  GalleryCollectionDto,
  LocaleCode,
  MemberDto,
  NeighborhoodArchiveItem,
  NavigationItemDto,
  ThemeTokens,
} from "@/types/cms";

export const fallbackTheme: ThemeTokens = defaultThemeTokens;

export const fallbackNavigation: Record<LocaleCode, NavigationItemDto[]> = {
  en: [
    { id: "nav-en-who", label: "WHO WE ARE", path: "/en/who-we-are", sortOrder: 1, isVisible: true },
    { id: "nav-en-what", label: "WHAT WE DO", path: "/en/what-we-do", sortOrder: 2, isVisible: true },
    { id: "nav-en-members", label: "FOUNDING MEMBERS", path: "/en/founding-members", sortOrder: 3, isVisible: true },
    { id: "nav-en-gallery", label: "PHOTO GALLERY", path: "/en/photo-gallery", sortOrder: 4, isVisible: true },
    { id: "nav-en-neighborhood-archive", label: "NEIGHBORHOOD ARCHIVE", path: "/en/neighborhood-archive", sortOrder: 5, isVisible: true },
  ],
  ar: [
    { id: "nav-ar-who", label: "من نحن", path: "/ar/who-we-are", sortOrder: 1, isVisible: true },
    { id: "nav-ar-what", label: "ماذا نفعل", path: "/ar/what-we-do", sortOrder: 2, isVisible: true },
    { id: "nav-ar-members", label: "الأعضاء المؤسسون", path: "/ar/founding-members", sortOrder: 3, isVisible: true },
    { id: "nav-ar-gallery", label: "معرض الصور", path: "/ar/photo-gallery", sortOrder: 4, isVisible: true },
  ],
};

export const fallbackFooter: Record<LocaleCode, FooterColumnDto[]> = {
  en: [
    {
      id: "footer-en-main",
      title: "LORA",
      sortOrder: 1,
      content: {
        text: "Luweibdeh old residents association",
        location: "Amman, Paris square",
        phone: "+962 7 7930 6500",
        email: "info@lorajo.org",
      },
      links: [],
    },
  ],
  ar: [
    {
      id: "footer-ar-main",
      title: "لورا",
      sortOrder: 1,
      content: {
        text: "جمعية سكان جبل اللويبدة القدامى",
        location: "عمان، ميدان باريس",
        phone: "+962 7 7930 6500",
        email: "info@lorajo.org",
      },
      links: [],
    },
  ],
};

function driveImage(fileId: string) {
  return `https://drive.google.com/thumbnail?id=${encodeURIComponent(fileId)}&sz=w2000`;
}

export const fallbackMembers: MemberDto[] = [
  {
    id: "member-omar",
    name: "Omar T. Alfaouri",
    slug: "omar-t-alfaouri",
    title: "Founding member",
    image: { src: driveImage("1tU7Uinvd_qygElWjFrqJw61TPSQMlLUN"), alt: "Omar T. Alfaouri" },
    sortOrder: 1,
  },
  {
    id: "member-wael",
    name: "Wael Hamza Smadi",
    slug: "wael-hamza-smadi",
    title: "Founding member",
    image: { src: driveImage("18kmiFoN8tNotoW2Gy6I_XpsBjBTWJi3d"), alt: "Wael Hamza Smadi" },
    sortOrder: 2,
  },
  {
    id: "member-saleem",
    name: "Saleem Quna",
    slug: "saleem-quna",
    title: "Founding member",
    image: { src: driveImage("1FmgWLUyVmzfYxZmGwMlpehJjTbIMFHF2"), alt: "Saleem Quna" },
    sortOrder: 3,
  },
  {
    id: "member-reem",
    name: "Reem Farkouh",
    slug: "reem-farkouh",
    title: "Founding member",
    image: { src: driveImage("1uoXPtOOZAoNgUoFPbuQBx21FiU3YhUtS"), alt: "Reem Farkouh" },
    sortOrder: 4,
  },
  {
    id: "member-rami",
    name: "Rami Daher",
    slug: "rami-daher",
    title: "Founding member",
    image: { src: driveImage("1oSOzLMCw2sYARGnsfutILkHvYmIA9bJy"), alt: "Rami Daher" },
    sortOrder: 5,
  },
  {
    id: "member-muneer",
    name: "Muneer Al Kurdi",
    slug: "muneer-al-kurdi",
    title: "Founding member",
    image: { src: driveImage("1OqpLEmR906zPDbu_uSAMP58WHD-WYQvt"), alt: "Muneer Al Kurdi" },
    sortOrder: 6,
  },
  {
    id: "member-marwan",
    name: "Marwan Al Manha",
    slug: "marwan-al-manha",
    title: "Founding member",
    image: { src: driveImage("1-86IrcvI3cpMEjh-7P9h6bNKRgkNCiVm"), alt: "Marwan Al Manha" },
    sortOrder: 7,
  },
  {
    id: "member-ali",
    name: "Ali Al Manha",
    slug: "ali-al-manha",
    title: "Founding member",
    image: { src: driveImage("1nJNZV-Z_5GlIjDFGxHFuL3JbzmzWKr2F"), alt: "Ali Al Manha" },
    sortOrder: 8,
  },
  {
    id: "member-majdolin",
    name: "Majdolin Ghazawi",
    slug: "majdolin-ghazawi",
    title: "Founding member",
    image: { src: driveImage("1QFqA-P5XGNuzwjDpBFZZupbRdi_YlG7a"), alt: "Majdolin Ghazawi" },
    sortOrder: 9,
  },
  {
    id: "member-abuazzam",
    name: "Marwan Abu Azzam",
    slug: "marwan-abu-azzam",
    title: "Founding member",
    image: { src: driveImage("1_4idRLfddXgrsYDh-QyF5gm1WDmea26k"), alt: "Marwan Abu Azzam" },
    sortOrder: 10,
  },
  {
    id: "member-daoud-khoury",
    name: "Daoud Khoury",
    slug: "daoud-khoury",
    title: "Founding member",
    image: { src: driveImage("1xzu3DYeonq02-3Xq7GsddUN6jYT--D_Q"), alt: "Daoud Khoury" },
    sortOrder: 11,
  },
  {
    id: "member-ghalib-qasem",
    name: "Ghalib Qasem",
    slug: "ghalib-qasem",
    title: "Founding member",
    image: { src: driveImage("1iYREvw0Djqbyh3LTGRJNL_R4oBt96uIQ"), alt: "Ghalib Qasem" },
    sortOrder: 12,
  },
  {
    id: "member-group",
    name: "Founding Members",
    slug: "founding-members-group",
    title: "Group photo",
    image: { src: driveImage("1fyoNiaRQ6Lrank965AII70-lQslwjpU_"), alt: "Founding Members" },
    sortOrder: 13,
  },
];

export const fallbackGallery: GalleryCollectionDto[] = [
  {
    id: "collection-historical",
    title: "HISTORICAL PHOTOS",
    slug: "historical-photos",
    description: "Archival views and memory fragments from Jabal Al-Luweibdeh.",
    sortOrder: 1,
    images: [
      { src: "/lora/gallery/square-de-paris.jpg", alt: "Paris Square", caption: "Paris Square" },
      { src: "/lora/gallery/luweibdeh-flower.jpg", alt: "Luweibdeh Flower", caption: "Luweibdeh Flower" },
      { src: "/lora/gallery/blue-house-4.jpg", alt: "Blue House", caption: "Blue House" },
    ],
  },
  {
    id: "collection-landmarks",
    title: "LANDMARKS",
    slug: "landmarks",
    description: "Civic, cultural, and architectural landmarks in the neighborhood.",
    sortOrder: 2,
    images: [
      { src: driveImage("17I4H8i9hcVV9_cMbs-fPlE7xHAkW_6X5"), alt: "2008 0217 PHOTOS NEW 0065", caption: "2008 0217 PHOTOS NEW 0065" },
      { src: driveImage("1QjQ7l9dUvjlEcBJFPrz5pvFXgdUYdgPt"), alt: "2008 0217 PHOTOS NEW 0052", caption: "2008 0217 PHOTOS NEW 0052" },
      { src: driveImage("1PpXb64VRZxjSDtEwbkX4-Gr83oNdqAme"), alt: "Luweibdeh Flower 3", caption: "Luweibdeh Flower 3" },
      { src: driveImage("1BzupM7C0_5q1tgvgRVdk9rwhAcnVg8tr"), alt: "Luweibdeh Flower 4", caption: "Luweibdeh Flower 4" },
      { src: driveImage("1EjUt2MrG8pLUzhvm4JKv2NP6SIdeV9np"), alt: "329A1183", caption: "329A1183" },
      { src: driveImage("1Qc1-ATBUlGKAjKdK3uUADLnqJ0j1S6_v"), alt: "329A1181", caption: "329A1181" },
      { src: driveImage("1zK4MfiX0Xb-sXmVaVt2dK05soRadaxdX"), alt: "329A1131", caption: "329A1131" },
      { src: driveImage("18gdj79JYtzB4CGEk6O6kr7PskMkZ-31S"), alt: "329A1133", caption: "329A1133" },
      { src: driveImage("1nYzBoS7jGlQ1HKnYnasWgy4sFnCz96E7"), alt: "329A1130", caption: "329A1130" },
      { src: driveImage("1wWDI5xRT-Bg2mBBLkMLB4zhiRZn_79Rg"), alt: "329A1115", caption: "329A1115" },
      { src: driveImage("1Fu4a89WG5wQUNNaJFHgqcQ4rUn23VH0t"), alt: "Panorama Amman from Jabal Al-Luweibdeh", caption: "Panorama Amman from Jabal Al-Luweibdeh" },
      { src: driveImage("1z-1dQuXGXw4FHk6c67c-SKslfg6mwQwU"), alt: "Luweibdeh Flower 1", caption: "Luweibdeh Flower 1" },
      { src: driveImage("1AHO6dcoDAvIv7HMpDgZolWefbuBBnuGH"), alt: "329A1170", caption: "329A1170" },
      { src: driveImage("1wIonAWc3sB5aqfkQ_IZ2h8PIKLKhLCNs"), alt: "329A1165", caption: "329A1165" },
      { src: driveImage("1kROBQ1uatl8r6qna3jamNVzLpJtam6wG"), alt: "329A1158", caption: "329A1158" },
      { src: driveImage("1CKYyPUuzCeXna-Fi1nZyMS7xPJfedJfM"), alt: "329A1156", caption: "329A1156" },
      { src: driveImage("19cNNJOrqApdy7VmPTNIfUzCpp_Y4ugDi"), alt: "329A1150", caption: "329A1150" },
      { src: driveImage("1WqkwtmUATydhAF8noPCk7EEdSQNpNyMJ"), alt: "329A1145", caption: "329A1145" },
      { src: driveImage("1RwFIcpbRvXjHvDALrPXrov42uJN8D75e"), alt: "329A1121", caption: "329A1121" },
      { src: driveImage("1l22H_xmtJzsjN7JxZ99ZyxbfT1svpvBK"), alt: "329A1118", caption: "329A1118" },
      { src: driveImage("173_bXGWe4xnC-79u0ND3eJ2whiW_c4u_"), alt: "329A1117", caption: "329A1117" },
      { src: driveImage("1rkbEd-ZJ4-eSJosk59X_4NNC4T1N-jyd"), alt: "329A1079", caption: "329A1079" },
      { src: driveImage("1d400__3SteNbSVWadD_TKeVYnpRyMqQV"), alt: "329A1086", caption: "329A1086" },
      { src: driveImage("11FKmxWLOmLgVnbn7eY7jugkImUR-zClb"), alt: "329A915", caption: "329A915" },
      { src: driveImage("1GNCPE7Ixg4FRjbRDU9J0UW4NC2Cim5uh"), alt: "329A1005", caption: "329A1005" },
      { src: driveImage("1hLz95fdURRGo6VivES06Q0iq1jp-xsIm"), alt: "329A0996", caption: "329A0996" },
      { src: driveImage("1mdIrxf5ZltC6ZbmQ_awy-KYP0gm1rjeF"), alt: "329A0909", caption: "329A0909" },
      { src: driveImage("1BEcr_nJKoTJB7HbHitwsdTmqpiWXVtS8"), alt: "329A0912", caption: "329A0912" },
      { src: driveImage("1yTKi6aVnaICDYCKmjkRfZ8MvbbPnZmzp"), alt: "329A1045", caption: "329A1045" },
      { src: driveImage("1fhtCCprY1_AFBGWLVRimyHJuQxRszS8C"), alt: "329A1104", caption: "329A1104" },
      { src: driveImage("1Ydo3wqfd8SBsyrcozU3tPU2yS6cNLS_k"), alt: "329A1102", caption: "329A1102" },
      { src: driveImage("1bMViwrKkZsFDjq7edpJBYT6IQ28AApMe"), alt: "329A1098", caption: "329A1098" },
      { src: driveImage("1bLGVYHm04E1qHEeNdNpaFroXA8NB46mU"), alt: "329A1096", caption: "329A1096" },
      { src: driveImage("17TayTXKTrFvC0eNVn55NuLXdt4xtUrkE"), alt: "329A1092", caption: "329A1092" },
      { src: driveImage("17PZfyN_lxXV6WRwYrRMlW5eArgxOAn8D"), alt: "329A1083", caption: "329A1083" },
      { src: driveImage("10LwLaf5nbRUKcfBH8Y_w6ofhDmwvZCTd"), alt: "329A1081", caption: "329A1081" },
      { src: driveImage("1T0-xfkyXoHzjYwk0kYw8L0rzl38Ymjvb"), alt: "9", caption: "9" },
      { src: driveImage("1SStqH3dl6Tcx2IBAkGjE-RswXWQJFpio"), alt: "329A1072", caption: "329A1072" },
      { src: driveImage("12P5PxNNHgxVDU0aMTp58EwI7DMXv5t8g"), alt: "329A1071", caption: "329A1071" },
      { src: driveImage("1XNPZW50Vigbu0s8pMssYk5OZNDSjGPBM"), alt: "329A1069", caption: "329A1069" },
      { src: driveImage("194eVTH5coS-niPf0kfnG_iLdwUyyPZ5_"), alt: "329A1051", caption: "329A1051" },
      { src: driveImage("1WPVOLe6XoRxLPnWcA8qq0zlXr242ikuK"), alt: "329A1038", caption: "329A1038" },
      { src: driveImage("1mWJ29Rwd-_OGY1HReUvFvML8G5yAZA0d"), alt: "329A1027", caption: "329A1027" },
      { src: driveImage("1nvxfUM6aeZzzzxhx01ByvgCULm7AtI8m"), alt: "8", caption: "8" },
      { src: driveImage("16tDiTSlr6kJcyqBTYTNRNPSrIfs2KlrC"), alt: "329A1025", caption: "329A1025" },
      { src: driveImage("1hIemZ70UUlEiTplkNrm3LmouwtA9mry7"), alt: "329A1024", caption: "329A1024" },
      { src: driveImage("1h0VWP7N3ckytrsyZ55Ac1jPWZAXVxMgJ"), alt: "329A1018", caption: "329A1018" },
      { src: driveImage("107TVomr--wd72jZO4J5hdts8MhsFrMox"), alt: "329A1012", caption: "329A1012" },
      { src: driveImage("1Dkh4s6teQiZDBO-Tp-SqwREs_OcO3VUp"), alt: "329A1010", caption: "329A1010" },
      { src: driveImage("1L-gBlIVB70on1lLWul2dPDaRy_HIBcup"), alt: "329A0987", caption: "329A0987" },
      { src: driveImage("1gJPy8hCAqYwkimiIWpvC5Vif2W-iXy-H"), alt: "329A0984", caption: "329A0984" },
      { src: driveImage("1MOL8iE1YQQ8bB1XwbmKoQOqXuQYXCzPJ"), alt: "329A0981", caption: "329A0981" },
      { src: driveImage("1UJ_3FY4DUlZ9rT_4VjxAGx8xB_C6BAVg"), alt: "329A0976", caption: "329A0976" },
      { src: driveImage("1rBISnKG2rmK1EsalJWXp9up62zC_B67Q"), alt: "Luweibdeh landmark", caption: "Luweibdeh landmark" },
      { src: driveImage("1HjMF2wZoeZhc3s1xQnf5sY4ZXgyn1nWU"), alt: "329A0969", caption: "329A0969" },
      { src: driveImage("1Tw2z8p1JhJQjJqfukJa4P6uFdyVyAJfq"), alt: "329A0968", caption: "329A0968" },
      { src: driveImage("1VE_Tga2y7hmkij5ET0W4mCcjZnJVFk3Q"), alt: "329A0967", caption: "329A0967" },
      { src: driveImage("1OFtLJm-fMpCncDVHrN6O1ImhctBHBvai"), alt: "329A0964", caption: "329A0964" },
      { src: driveImage("1S007gPBVt_kL37q_u0m4yN9TKdAvVIBU"), alt: "329A0963", caption: "329A0963" },
      { src: driveImage("1Ks_e6rpoDr-F9Q3CI8W864XSWhUF8VY4"), alt: "329A0956", caption: "329A0956" },
    ],
  },
  {
    id: "collection-figures",
    title: "FAMOUS FIGURES",
    slug: "famous-figures",
    description: "Residents and public figures connected to Luweibdeh history.",
    sortOrder: 3,
    images: [
      { src: driveImage("1yV3msoYxSZt10Y4L5VqRs3NxHMTrMPiJ"), alt: "Famous figure", caption: "Famous figure" },
      { src: driveImage("1TvEWapMGby99Yr9j8IAV6XMQVmTOMXnt"), alt: "Zuhair Ajlouni", caption: "Zuhair Ajlouni" },
      { src: driveImage("13XP-IwvyBryHz3nQjJZRhr3JL_tgBCzl"), alt: "Sameer Rifai", caption: "Sameer Rifai" },
      { src: driveImage("1xII54ggqYiN6NTrKT3RZUS0jKGmaGkP8"), alt: "Zaid Rifai", caption: "Zaid Rifai" },
      { src: driveImage("1wllsXlAHxPHEupfno-91epMYUhE3lIU3"), alt: "Taisir Mohammad Ali Zeinab Al Faouri", caption: "Taisir Mohammad Ali Zeinab Al Faouri" },
      { src: driveImage("191CDI63tILBH_ukjXhXVG92yyySG0LHc"), alt: "Suliman Nabelsi", caption: "Suliman Nabelsi" },
      { src: driveImage("1Bt82ATEiYP5I8hXJFGT0wANYDHAZvyu-"), alt: "Suliman Mashini", caption: "Suliman Mashini" },
      { src: driveImage("1o0gdeZNRZ2rit-aXf7IVtZ63SUYTLFGg"), alt: "Subhi Haj Hassan", caption: "Subhi Haj Hassan" },
      { src: driveImage("1W53rf_Omf4rKsYleWpM3KPXVJj934OaB"), alt: "Sheik Nadeem Mallah", caption: "Sheik Nadeem Mallah" },
      { src: driveImage("18STPlPdOyiN5tBj3XjTkii7hsx0Ccbtv"), alt: "Shareef Jameel Bin Nasser", caption: "Shareef Jameel Bin Nasser" },
      { src: driveImage("1G__2F3aoXw8kXRrCDSTbbR0T-3hnzkaQ"), alt: "Sami Shair", caption: "Sami Shair" },
      { src: driveImage("1e0_Rc6wjsN1epy00MPTashPH3SlU8a9R"), alt: "Samir Rifai I", caption: "Samir Rifai I" },
      { src: driveImage("1NTGfOrhy2LC7sRgWASuF7vfP4EO5I8j0"), alt: "Rajab Khashman", caption: "Rajab Khashman" },
      { src: driveImage("1fj-oUsdPkQ6WSM5IX29_Xv_ibK1N7_Fi"), alt: "Rafii Shaheen", caption: "Rafii Shaheen" },
      { src: driveImage("107gryrB-cA7SbeMFedqM-8UiUVSawlFk"), alt: "Princess Haya Bint Abdullah I", caption: "Princess Haya Bint Abdullah I" },
      { src: driveImage("1yeOkyGpum8ABsp_o1sa8iCx6iP9VJvlk"), alt: "Omran Maita", caption: "Omran Maita" },
      { src: driveImage("1mZV8P6qcy5Zqc7A_pB7H40-pXjcCauHw"), alt: "Mwafaq Al Salti", caption: "Mwafaq Al Salti" },
      { src: driveImage("101BXSZmjJjnnwvW3KuVita1iFdpsGWlQ"), alt: "Mousa Al Saket", caption: "Mousa Al Saket" },
      { src: driveImage("1WT8dABH0KQuIeMM0IJGyBg_9cLwr_SOn"), alt: "Mounis Razzaz", caption: "Mounis Razzaz" },
      { src: driveImage("1SYOEP7_A-RjYPHIk0Jc4WQD-vmS6eJ0r"), alt: "Mohammad Ali Zeinab Al Faouri", caption: "Mohammad Ali Zeinab Al Faouri" },
      { src: driveImage("1pd9StSvv2YmF156vXQYxebQs48WznqMQ"), alt: "Mohammad Ali Ajlouni", caption: "Mohammad Ali Ajlouni" },
      { src: driveImage("1QFDbi27CGkTgpJO8sjKODUDdMlbru-rr"), alt: "Mazen Ajlouni", caption: "Mazen Ajlouni" },
      { src: driveImage("1VHqGvWtvzRPExv62NDr_D80R0EdAi7QQ"), alt: "Marwan Abu Azzam", caption: "Marwan Abu Azzam" },
      { src: driveImage("1JrKnDBUDDxtkO7f4dhZqflrmgB32wQ1z"), alt: "Khalil Abu Manneh", caption: "Khalil Abu Manneh" },
      { src: driveImage("126LpBNJAKsmwGcZ2d5_pnPM6aMMTij97"), alt: "Kazem Kotob", caption: "Kazem Kotob" },
      { src: driveImage("1jCs5Pv2LM2HbvXXhUN1pgDwAx_AbPKrU"), alt: "Mousa Saket", caption: "Mousa Saket" },
      { src: driveImage("1bTOTOsqRPhtS9nFucaJiN7qDrJHTWm5t"), alt: "Issam Ajlouni", caption: "Issam Ajlouni" },
      { src: driveImage("1FaUIXz5GI4unN5Y2c5lNpf30scJxc81N"), alt: "Hussein Tarawneh", caption: "Hussein Tarawneh" },
      { src: driveImage("1mO3uOVYRAJWczWb9HwYwqzlWevAF-6LF"), alt: "Husni Fareez", caption: "Husni Fareez" },
      { src: driveImage("1YVI6L_1xVqNmGplwZJJuzULt-ODe7_AQ"), alt: "Hanna Khoury", caption: "Hanna Khoury" },
      { src: driveImage("1eQ8GUC1LddbRvyLPfhdlRK_5SElZhxgQ"), alt: "Fouad Sleem", caption: "Fouad Sleem" },
      { src: driveImage("1LxWf6EyY3SZXeD_iSNQcLGmBFW241O1N"), alt: "Fouad Al Khateeb", caption: "Fouad Al Khateeb" },
      { src: driveImage("1lWnwrjkhyXTHIQhSn9bEPbXZxSUgZiZV"), alt: "Firas Ajlouni3", caption: "Firas Ajlouni3" },
      { src: driveImage("12kXTp7Qd_BhPuCVCO-zDQtiUUFJV12EX"), alt: "Firas Ajlouni", caption: "Firas Ajlouni" },
      { src: driveImage("1AlBcFEBCSaw1Ei4Nil0G8iAx1KaXuRSx"), alt: "Firas Ajloouni Muwafaq Salti", caption: "Firas Ajloouni Muwafaq Salti" },
      { src: driveImage("1OYAvbLOypFDv0eukY0s4EKqqm5sP5jOI"), alt: "Fareed Khalaf", caption: "Fareed Khalaf" },
      { src: driveImage("1FAYWN5Wv_hMxN8ci11YmyAQ5xX-F71AD"), alt: "Falah Madadha", caption: "Falah Madadha" },
      { src: driveImage("17Tb4AzyznMeB2lwm_A2PLcyua5rDGVkR"), alt: "Faek Halazoon", caption: "Faek Halazoon" },
      { src: driveImage("1sKs-Wp8ePjmOola4Y8VyhsTO1bhhfo-q"), alt: "Emil Salim Farkooh", caption: "Emil Salim Farkooh" },
      { src: driveImage("1EKNX5OXBxhtMlF9QaKBvRs3RpcBfd405"), alt: "Dr. Mamdooh Abbadi", caption: "Dr. Mamdooh Abbadi" },
      { src: driveImage("1y2Z7mHE-aQEX0OtTOImuCvqehF3DTJMx"), alt: "Dr. Zaid Hamzeh", caption: "Dr. Zaid Hamzeh" },
      { src: driveImage("1KBNvcV1h4slMBypMKy6UIxUTckVk40Pu"), alt: "Dr. Omar Razza", caption: "Dr. Omar Razza" },
      { src: driveImage("1XzFU2fyYTrHqEiIhkgbJuL20dFTz3Z8F"), alt: "Dr. Muneef Razzaz", caption: "Dr. Muneef Razzaz" },
      { src: driveImage("1tVenFiqmq-h81GZb7yThUCFVcxGFzfPM"), alt: "Dr. Adnan Masnat", caption: "Dr. Adnan Masnat" },
      { src: driveImage("1UO49QUwXeYAJlnfzLDslPXSVld4Supuv"), alt: "Dr. Abdelrahman Shokair", caption: "Dr. Abdelrahman Shokair" },
      { src: driveImage("1Fibuu8DrEDb-Pj8uXsypqRpsWe19TFCp"), alt: "Dr. Saliba Beqaeen", caption: "Dr. Saliba Beqaeen" },
      { src: driveImage("15OKQ8jEJgCNNZBOlG7HE18Ii8e-01lD5"), alt: "Baderdin Zaza", caption: "Baderdin Zaza" },
      { src: driveImage("1O77ru_iQSlZJ5BoG2RYYvBk8oEVxOAuF"), alt: "Akef Al Fayez", caption: "Akef Al Fayez" },
      { src: driveImage("1FfWv1K8ha2NHOj3vR2WEm-XgoJdlHBND"), alt: "Abdel Rahman Abu Hassan", caption: "Abdel Rahman Abu Hassan" },
      { src: driveImage("1fzn0Sp1tftl6FleiO5Z2Di5c_Pxd7jXM"), alt: "Abdel Khader Tash", caption: "Abdel Khader Tash" },
      { src: driveImage("1k1RG7IEjI0GBgOkirujm-IWqyR_zhVHP"), alt: "Abdel Halim Nimmer Al Hmood", caption: "Abdel Halim Nimmer Al Hmood" },
      { src: driveImage("1FJbIpDRltvY6pvQTbIojdam8dosgfo7D"), alt: "Abdel Khader Al Jundi", caption: "Abdel Khader Al Jundi" },
      { src: driveImage("1fgyIzPT-Z_u4e9D5g56p65-F-QhPtEKy"), alt: "Abbas Mirza", caption: "Abbas Mirza" },
      { src: driveImage("1JVqYXxjWGI3uJJ_WFwkQc5SyuAauobpt"), alt: "Frederick Peake", caption: "Frederick Peake" },
      { src: driveImage("1KsRbM3ib9K1n9pdORFBk4xiH4IN7xqLY"), alt: "Nimer Hmood", caption: "Nimer Hmood" },
    ],
  },
];

export const fallbackNeighborhoodArchive: NeighborhoodArchiveItem[] = [
  {
    id: "archive-paris-square",
    name: "Paris Square",
    text: "A civic meeting point in Jabal Al-Luweibdeh.",
    mediaType: "IMAGE",
    src: "/lora/gallery/square-de-paris.jpg",
    thumbnail: "/lora/gallery/square-de-paris.jpg",
    folder: "Fallback archive",
  },
  {
    id: "archive-dar-al-anda",
    name: "Dar Al-Anda",
    text: "A cultural landmark in the neighborhood archive.",
    mediaType: "IMAGE",
    src: "/lora/gallery/dar-al-anda-art-gallery.jpg",
    thumbnail: "/lora/gallery/dar-al-anda-art-gallery.jpg",
    folder: "Fallback archive",
  },
  {
    id: "archive-blue-house",
    name: "Blue House",
    text: "Architectural memory from Luweibdeh.",
    mediaType: "IMAGE",
    src: "/lora/gallery/blue-house-4.jpg",
    thumbnail: "/lora/gallery/blue-house-4.jpg",
    folder: "Fallback archive",
  },
];

export const fallbackPages: Record<LocaleCode, Record<string, CmsPage>> = {
  en: {
    home: {
      id: "page-en-home",
      locale: "en",
      slug: "home",
      title: "LORA",
      seoTitle: "LORA - Luweibdeh Old Residents Association",
      seoDescription: "LORA preserves Jabal Al-Luweibdeh's historical architecture, greenery, and cultural heritage.",
      status: "PUBLISHED",
      sections: [
        {
          id: "home-hero",
          type: "hero",
          variant: "editorial_fullscreen",
          sortOrder: 1,
          isVisible: true,
          content: {
            eyebrow: "Luweibdeh Old Residents Association",
            title: "LORA",
            subtitle: "Luweibdeh Old Residents Association",
            tagline: "Our cultural heritage is our identity",
            body: "A civic association preserving Jabal Al-Luweibdeh's historical architecture, greenery, cultural memory, and community life.",
            image: "/lora/gallery/luweibdeh-flower.jpg",
            logo: "/lora/brand/lora-logo.png",
            cta: { label: "Read More", href: "/en/who-we-are" },
          },
          settings: {
            imagePlacement: "background",
            overlayOpacity: 0.45,
            parallax: true,
            titleTop: "LORA",
            titleBottom: "LUWEIBDEH",
            accentHex: "#01963c",
            defaultAspect: 16 / 9,
            heroScrubFrames: [
              "/lora/gallery/luweibdeh-flower.jpg",
              "/lora/gallery/square-de-paris.jpg",
              "/lora/gallery/dar-al-anda-art-gallery.jpg",
              "/lora/gallery/blue-house-4.jpg",
              "/lora/gallery/alsaadi-mosque.jpg",
              "/lora/gallery/luzmila-hospital.jpg",
              "/lora/gallery/dscf0022.jpg",
              "/lora/gallery/luweibdeh-flower-2.jpg",
            ],
          },
          background: { token: "black" },
        },
        {
          id: "home-marquee",
          type: "text_marquee",
          variant: "heritage_line",
          sortOrder: 2,
          isVisible: true,
          content: { items: ["Heritage Preservation", "Community Engagement", "Sustainability", "Equity"] },
          settings: { speed: 32 },
          spacing: { top: "small", bottom: "small" },
          background: { token: "parchment" },
        },
        {
          id: "home-story",
          type: "heritage_story",
          variant: "overlapping_editorial",
          sortOrder: 3,
          isVisible: true,
          content: {
            label: "What we do ?",
            title: "Protecting a neighborhood without freezing it in time.",
            body: "LORA aims to enhance community engagement and improve services in the neighborhood in cultural, environmental, and heritage aspects.",
            image: "/lora/gallery/square-de-paris.jpg",
            cta: { label: "Read More", href: "/en/what-we-do" },
          },
          settings: { imagePlacement: "right", cardStyle: "stone_border" },
          background: { token: "softWhite" },
        },
        {
          id: "home-gallery",
          type: "gallery_grid",
          variant: "lightbox_grid",
          sortOrder: 4,
          isVisible: true,
          content: {
            title: "Luweibdeh in fragments",
            items: [
              { src: "/lora/gallery/square-de-paris.jpg", alt: "Paris Square", caption: "Paris Square" },
              { src: "/lora/gallery/dar-al-anda-art-gallery.jpg", alt: "Dar Al-Anda", caption: "Dar Al-Anda" },
              { src: "/lora/gallery/blue-house-4.jpg", alt: "Blue House", caption: "Blue House" },
              { src: "/lora/gallery/alsaadi-mosque.jpg", alt: "Al Saadi Mosque", caption: "Al Saadi Mosque" },
              { src: "/lora/gallery/luweibdeh-flower.jpg", alt: "Luweibdeh Flower", caption: "Luweibdeh Flower" },
              { src: "/lora/gallery/luzmila-hospital.jpg", alt: "Luzmila Hospital", caption: "Luzmila Hospital" },
              { src: "/lora/gallery/dscf0022.jpg", alt: "Luweibdeh street detail", caption: "Street detail" },
            ],
          },
          settings: { columns: 4, lightbox: true },
          background: { token: "parchment" },
        },
        {
          id: "home-newsletter",
          type: "newsletter_signup",
          variant: "centered_minimal",
          sortOrder: 5,
          isVisible: true,
          content: {
            title: "Stay close to the neighborhood.",
            body: "Receive LORA updates on cultural, environmental, and heritage initiatives.",
            buttonLabel: "Subscribe",
          },
          settings: {},
          background: { token: "black" },
        },
      ],
    },
    "who-we-are": {
      id: "page-en-who",
      locale: "en",
      slug: "who-we-are",
      title: "LORA JO",
      seoTitle: "Who We Are - LORA",
      seoDescription: "The Association of Old Residents of Jabal Al-Luweibdeh.",
      status: "PUBLISHED",
      sections: [
        {
          id: "who-hero",
          type: "hero",
          variant: "centered_minimal",
          sortOrder: 1,
          isVisible: true,
          content: {
            title: "LORA JO",
            subtitle: "The Association of Old Residents of Jabal Al-Luweibdeh (LORA)",
          },
          settings: {},
        },
        {
          id: "who-body",
          type: "rich_text",
          variant: "editorial_body",
          sortOrder: 2,
          isVisible: true,
          content: {
            body: [
              "Established in 2024 at the initiative of a group of long-time residents, LORA is dedicated to preserving Luweibdeh's historical buildings, natural landscape, streets, and greenery in the face of the assault of modern trends of architectural urbanization and serving its community members.",
              "Its main activities include supporting all private and public initiatives to make this neighborhood attractive for cultural and artistic activities.",
              "LORA aspires to create a dynamic, engaged community that honors its past while looking forward to a sustainable and promising future.",
              "LORA voluntarily and equitably provides services to all its members, with no intention of generating financial profit or offering personal benefits, either directly or indirectly to its board members. It consciously avoids political, sectarian, and personal agendas.",
            ],
          },
          settings: {},
        },
      ],
    },
    "what-we-do": {
      id: "page-en-what",
      locale: "en",
      slug: "what-we-do",
      title: "What we do ?",
      seoTitle: "What We Do - LORA",
      seoDescription: "LORA community, heritage, environmental, and local economic initiatives.",
      status: "PUBLISHED",
      sections: [
        {
          id: "what-hero",
          type: "hero",
          variant: "split_text_image",
          sortOrder: 1,
          isVisible: false,
          content: { title: "What we do ?", image: "/lora/gallery/dar-al-anda-art-gallery.jpg" },
          settings: {},
        },
        {
          id: "what-body",
          type: "rich_text",
          variant: "what_we_do_gallery",
          sortOrder: 2,
          isVisible: true,
          content: {
            title: "What we do ?",
            subtitle: "LORA strengthens belonging, protects shared heritage, and supports practical community initiatives.",
            images: [
              { src: "/lora/gallery/dar-al-anda-art-gallery.jpg", alt: "Dar Al-Anda", caption: "Cultural activity" },
              { src: "/lora/gallery/square-de-paris.jpg", alt: "Paris Square", caption: "Public space" },
              { src: "/lora/gallery/alsaadi-mosque.jpg", alt: "Al Saadi Mosque", caption: "Heritage landmark" },
              { src: "/lora/gallery/blue-house-4.jpg", alt: "Blue House", caption: "Historical architecture" },
            ],
            body: [
              "The founding committee has outlined two primary objectives:",
              "1. Fostering a Sense of Belonging: LORA aims to enhance community engagement and improve services in the neighborhood in cultural, environmental, and heritage aspects.",
              "This will be achieved through research, documentation, skill development programs, lectures, seminars, and workshops tailored to the community, especially younger generations.",
              "LORA will spare no effort to analyze the neighborhood's challenges and issues and work with proper authorities to address them.",
              "2. Organizing Small Income-Generating Projects: LORA seeks to collaborate with residents to operate small-scale projects that benefit the community and individual participants.",
              "Programs include enhancing the economic well-being of Al-Luweibdeh residents, creating new job opportunities, and hosting a seasonal bazaar in collaboration with specialized local organizations.",
            ],
          },
          settings: {},
        },
      ],
    },
    "founding-members": {
      id: "page-en-members",
      locale: "en",
      slug: "founding-members",
      title: "LORA",
      seoTitle: "Founding Members - LORA",
      seoDescription: "LORA founding members.",
      status: "PUBLISHED",
      sections: [
        {
          id: "members-hero",
          type: "hero",
          variant: "centered_minimal",
          sortOrder: 1,
          isVisible: false,
          content: {
            title: "LORA",
            subtitle: "Dedication. Expertise. Passion.",
            oldImportedContent:
              "This is your Team section. It's a great place to introduce your team and talk about what makes it special, such as your culture or work philosophy. Don't be afraid to illustrate personality and character to help users connect with your team.",
          },
          settings: { showOldImportedContent: false },
        },
        {
          id: "members-grid",
          type: "member_grid",
          variant: "team_showcase",
          sortOrder: 2,
          isVisible: true,
          content: { title: "Founding members", subtitle: "Dedication. Expertise. Passion.", source: "members" },
          settings: {},
        },
      ],
    },
    "photo-gallery": {
      id: "page-en-gallery",
      locale: "en",
      slug: "photo-gallery",
      title: "PHOTO GALLERY",
      seoTitle: "Photo Gallery - LORA",
      seoDescription: "Historical photos, landmarks, and famous figures connected to Jabal Al-Luweibdeh.",
      status: "PUBLISHED",
      sections: [
        {
          id: "gallery-hero",
          type: "hero",
          variant: "centered_minimal",
          sortOrder: 1,
          isVisible: false,
          content: { title: "PHOTO GALLERY" },
          settings: {},
        },
        {
          id: "gallery-collections",
          type: "gallery_masonry",
          variant: "staggered_grid",
          sortOrder: 2,
          isVisible: true,
          content: {
            title: "PHOTO GALLERY",
            subtitle: "Historical photos, landmarks, and public memory from Jabal Al-Luweibdeh.",
            collections: ["HISTORICAL PHOTOS", "LANDMARKS", "FAMOUS FIGURES"],
          },
          settings: {},
        },
      ],
    },
    "neighborhood-archive": {
      id: "page-en-neighborhood-archive",
      locale: "en",
      slug: "neighborhood-archive",
      title: "Neighborhood Archive",
      seoTitle: "Neighborhood Archive - LORA",
      seoDescription: "A searchable library of neighborhood names, photos, videos, and memory fragments from Jabal Al-Luweibdeh.",
      status: "PUBLISHED",
      sections: [
        {
          id: "neighborhood-archive-main",
          type: "neighborhood_archive",
          variant: "searchable_library",
          sortOrder: 1,
          isVisible: true,
          content: {
            title: "Neighborhood Archive",
            subtitle: "Search names, photographs, videos, and memory fragments connected to Jabal Al-Luweibdeh.",
          },
          settings: {},
          background: { token: "softWhite" },
        },
      ],
    },
  },
  ar: {
    home: {
      id: "page-ar-home",
      locale: "ar",
      slug: "home",
      title: "لورا",
      seoTitle: "لورا - جمعية سكان جبل اللويبدة القدامى",
      seoDescription: "جمعية سكان جبل اللويبدة القدامى.",
      status: "PUBLISHED",
      sections: [
        {
          id: "home-hero-ar",
          type: "hero",
          variant: "editorial_fullscreen",
          sortOrder: 1,
          isVisible: true,
          content: {
            eyebrow: "جمعية سكان جبل اللويبدة القدامى",
            title: "لورا",
            subtitle: "جمعية سكان جبل اللويبدة القدامى",
            tagline: "تراثنا الثقافي هو هويتنا",
            body: "جمعية مجتمعية تعمل على حفظ عمارة جبل اللويبدة التاريخية وخضرته وذاكرته الثقافية.",
            image: "/lora/gallery/luweibdeh-flower.jpg",
            logo: "/lora/brand/lora-logo.png",
            cta: { label: "اقرأ المزيد", href: "/ar/who-we-are" },
          },
          settings: {
            imagePlacement: "background",
            overlayOpacity: 0.45,
            parallax: true,
            titleTop: "LORA",
            titleBottom: "LUWEIBDEH",
            accentHex: "#01963c",
            defaultAspect: 16 / 9,
            heroScrubFrames: [
              "/lora/gallery/luweibdeh-flower.jpg",
              "/lora/gallery/square-de-paris.jpg",
              "/lora/gallery/dar-al-anda-art-gallery.jpg",
              "/lora/gallery/blue-house-4.jpg",
              "/lora/gallery/alsaadi-mosque.jpg",
              "/lora/gallery/luzmila-hospital.jpg",
              "/lora/gallery/dscf0022.jpg",
              "/lora/gallery/luweibdeh-flower-2.jpg",
            ],
          },
          background: { token: "black" },
        },
        {
          id: "home-story-ar",
          type: "heritage_story",
          variant: "overlapping_editorial",
          sortOrder: 2,
          isVisible: true,
          content: {
            label: "ماذا نفعل؟",
            title: "حفظ الحي مع إبقائه حيا.",
            body: "تسعى لورا إلى تعزيز انتماء المجتمع وتحسين الخدمات في الجوانب الثقافية والبيئية والتراثية.",
            image: "/lora/gallery/square-de-paris.jpg",
            cta: { label: "اقرأ المزيد", href: "/ar/what-we-do" },
          },
          settings: {},
        },
      ],
    },
    "who-we-are": {
      id: "page-ar-who",
      locale: "ar",
      slug: "who-we-are",
      title: "لورا",
      seoTitle: "من نحن - لورا",
      seoDescription: "جمعية سكان جبل اللويبدة القدامى.",
      status: "PUBLISHED",
      sections: [
        {
          id: "who-ar",
          type: "hero",
          variant: "centered_minimal",
          sortOrder: 1,
          isVisible: true,
          content: { title: "لورا", subtitle: "جمعية سكان جبل اللويبدة القدامى" },
          settings: {},
        },
      ],
    },
    "what-we-do": {
      id: "page-ar-what",
      locale: "ar",
      slug: "what-we-do",
      title: "ماذا نفعل",
      seoTitle: "ماذا نفعل - لورا",
      seoDescription: "مبادرات لورا التراثية والمجتمعية.",
      status: "PUBLISHED",
      sections: [
        {
          id: "what-ar",
          type: "hero",
          variant: "centered_minimal",
          sortOrder: 1,
          isVisible: true,
          content: { title: "ماذا نفعل؟" },
          settings: {},
        },
      ],
    },
    "founding-members": {
      id: "page-ar-members",
      locale: "ar",
      slug: "founding-members",
      title: "الأعضاء المؤسسون",
      seoTitle: "الأعضاء المؤسسون - لورا",
      seoDescription: "الأعضاء المؤسسون لجمعية لورا.",
      status: "PUBLISHED",
      sections: [
        {
          id: "members-ar",
          type: "member_grid",
          variant: "team_showcase",
          sortOrder: 1,
          isVisible: true,
          content: { title: "الأعضاء المؤسسون", subtitle: "تفان. خبرة. شغف.", source: "members" },
          settings: {},
        },
      ],
    },
    "photo-gallery": {
      id: "page-ar-gallery",
      locale: "ar",
      slug: "photo-gallery",
      title: "معرض الصور",
      seoTitle: "معرض الصور - لورا",
      seoDescription: "صور تاريخية ومعالم وشخصيات من جبل اللويبدة.",
      status: "PUBLISHED",
      sections: [
        {
          id: "gallery-ar",
          type: "gallery_masonry",
          variant: "staggered_grid",
          sortOrder: 1,
          isVisible: true,
          content: {
            title: "معرض الصور",
            subtitle: "صور تاريخية ومعالم وذاكرة عامة من جبل اللويبدة.",
            collections: ["HISTORICAL PHOTOS", "LANDMARKS", "FAMOUS FIGURES"],
          },
          settings: {},
        },
      ],
    },
    "neighborhood-archive": {
      id: "page-ar-neighborhood-archive",
      locale: "ar",
      slug: "neighborhood-archive",
      title: "Neighborhood Archive",
      seoTitle: "Neighborhood Archive - LORA",
      seoDescription: "A searchable library of neighborhood names, photos, videos, and memory fragments from Jabal Al-Luweibdeh.",
      status: "PUBLISHED",
      sections: [
        {
          id: "neighborhood-archive-ar-main",
          type: "neighborhood_archive",
          variant: "searchable_library",
          sortOrder: 1,
          isVisible: true,
          content: {
            title: "Neighborhood Archive",
            subtitle: "Search names, photographs, videos, and memory fragments connected to Jabal Al-Luweibdeh.",
          },
          settings: {},
          background: { token: "softWhite" },
        },
      ],
    },
  },
};
